version: "3.7"
services:
    morfeu:
        container_name: morfeu-webapp
        build:
            context: ../morfeu
            args:
                MAVEN_OPTS: ${MAVEN_OPTS_ARG}
                MAVEN_CENTRAL_MIRROR: ${MAVEN_CENTRAL_MIRROR:-none}
            extra_hosts:
               - "${MAVEN_CENTRAL_MIRROR_HOST:none}=${MAVEN_CENTRAL_MIRROR_IP:127.0.0.1}"
        image: morfeu:${MORFEU_VERSION:v0.8.20}
        environment:
          - __RESOURCES_PREFIX=http://snow-package:8990/ 
          - __PROXY_PREFIX=http://snow-package:8990
        ports:
            - 8980:8980
    snowpackage_site:
        container_name: snowpackage-site
        build: .
        image: snowpackage-site:v0.8.11
        ports:
            - 3010:3010
        volumes:
            - site-content:/site
    snowpackage:
        container_name: snow-package
        build:
            context: ../snow-package
            args:
                MAVEN_OPTS: ${MAVEN_OPTS_ARG}
                MORFEU_VERSION: ${MORFEU_VERSION:-v0.8.20}
        image: snow-package:0.8.20
        environment:
         - __RESOURCES_PREFIX=file:///site/src/snowpackage/
         - __PROXY_PREFIX=http://snowpackage-site:3010
        ports:
            - 8990:8990
        volumes:
            - site-content:/site
volumes:
    site-content:
