version: "3.7"
services:
    squid:
        container_name: squid
        image: datadog/squid
    morfeu:
        container_name: morfeu-webapp
        build: 
            context: ../morfeu
            args:
                MAVEN_OPTS: "-DproxySet=true -Dhttp.proxyHost=squid -Dhttp.proxyPort=3128 -Djava.net.useSystemProxies=true"
                HTTP_PROXY_: "http://squid:3128/"
        image: morfeu:0.6.2
        ports: 
            - "8980:8980"
        environment:
            RESOURCES_PREFIX: http://snow-package:8990/
            PROXY_PREFIX: http://snow-package:8990
    snowpackage:
        container_name: snow-package
        build:
            context: ../snow-package
            args:
                MAVEN_OPTS: "-DproxySet=true -Dhttp.proxyHost=squid -Dhttp.proxyPort=3128 -Djava.net.useSystemProxies=true"
                HTTP_PROXY_: "http://squid:3128/"
        image: snow-package:0.0.2
        ports: 
            - "8990:8990"
        environment:
            RESOURCES_PREFIX: file:///site/
            PROXY_PREFIX: http://snow-package-site:3010
        volumes:
            - type: bind
              source: src
              target: /site
    snowpackage_site:
        container_name: snow-package-site
        build: .
        image: snowpackage-site:0.0.2
        ports: 
            - "3010:3010"
        volumes:
            - type: bind
              source: src
              target: /site
