version: "3.7"
services:
    morfeu:
        container_name: morfeu-webapp
        build:
            context: ../morfeu
            args:
                MAVEN_OPTS: ${MAVEN_OPTS_ARG}
                HTTP_PROXY_: ${PROXY_ARG}
        image: morfeu:0.6.2
        command: -D__RESOURCES_PREFIX=http://snow-package:8990/ -D__PROXY_PREFIX=http://snow-package:8990
        ports:
            - 8980:8980
    snowpackage_site:
        container_name: snowpackage-site
        build: .
        image: snowpackage-site:0.0.2
        ports:
            - 3010:3010
        volumes:
            - site-content:/site
    snowpackage:
        container_name: snow-package
        build:
            context: ../snow-package
            args:
                MAVEN_OPTS: ${MAVEN_OPTS_ARG}
                HTTP_PROXY_: ${PROXY_ARG}
        image: snow-package:0.0.2
        command: -D__RESOURCES_PREFIX=file:///site/src/snowpackage/ -D__PROXY_PREFIX=http://snowpackage-site:3010
        ports:
            - 8990:8990
        volumes:
            - site-content:/site
volumes:
    site-content:
